id = "hosts"
name = "Hosts"
version = "0.0.1"
schema_version = 1
authors = ["Pavel Vlasikhin <pavel@vlasikhin.com>"]
description = "Syntax highlighting for /etc/hosts files"
repository = "https://github.com/vlasikhin/zed-hosts"

[grammars.hosts]
repository = "https://github.com/vlasikhin/tree-sitter-hosts"
rev = "5ab61f0130c0278a98de91ecccb6b3ca35988594"
